name: Generate Snake Animation

on:
  schedule:
    # Jalan tiap hari jam 00:00 UTC (jam 07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: {} # bisa di-trigger manual dari tab Actions

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (light & dark)
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: RaiXvnm99
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push hasil ke branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
